//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.employee_timesheet = new HashSet<employee_timesheet>();
        }
    
        public int employee_id { get; set; }
        public string employee_serial { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string email_address { get; set; }
        public string gender { get; set; }
        public string contact_number { get; set; }
        public string sss { get; set; }
        public string pagibig { get; set; }
        public string philhealth { get; set; }
        public string marital_status { get; set; }
        public Nullable<System.DateTime> date_hire { get; set; }
        public Nullable<System.DateTime> date_resign { get; set; }
        public int ref_shift_id { get; set; }
        public int ref_department_id { get; set; }
        public string fingerprint { get; set; }
        public Nullable<decimal> basic_pay { get; set; }
        public Nullable<System.DateTime> date_deleted { get; set; }
    
        public virtual ref_department ref_department { get; set; }
        public virtual ref_shift ref_shift { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_timesheet> employee_timesheet { get; set; }
    }
}
