//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PayrollDBEntities : DbContext
    {
        public PayrollDBEntities()
            : base("name=PayrollDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<employee_timesheet> employee_timesheet { get; set; }
        public virtual DbSet<ref_calendar_activity> ref_calendar_activity { get; set; }
        public virtual DbSet<ref_day_type> ref_day_type { get; set; }
        public virtual DbSet<ref_department> ref_department { get; set; }
        public virtual DbSet<ref_pagibig> ref_pagibig { get; set; }
        public virtual DbSet<ref_payroll_status> ref_payroll_status { get; set; }
        public virtual DbSet<ref_philhealth> ref_philhealth { get; set; }
        public virtual DbSet<ref_shift> ref_shift { get; set; }
        public virtual DbSet<ref_shift_detail> ref_shift_detail { get; set; }
        public virtual DbSet<ref_sss> ref_sss { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<timesheet_log> timesheet_log { get; set; }
    }
}
