//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_shift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ref_shift()
        {
            this.employee = new HashSet<employee>();
            this.employee_timesheet = new HashSet<employee_timesheet>();
            this.ref_shift_detail = new HashSet<ref_shift_detail>();
        }
    
        public int ref_shift_id { get; set; }
        public string shift_name { get; set; }
        public Nullable<System.TimeSpan> shift_in { get; set; }
        public Nullable<System.TimeSpan> shift_out { get; set; }
        public Nullable<System.TimeSpan> break_in { get; set; }
        public Nullable<System.TimeSpan> break_out { get; set; }
        public Nullable<decimal> break_hour { get; set; }
        public Nullable<decimal> required_hour { get; set; }
        public Nullable<System.DateTime> date_deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee> employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_timesheet> employee_timesheet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ref_shift_detail> ref_shift_detail { get; set; }
    }
}
