//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_pagibig
    {
        public int ref_pagibig_id { get; set; }
        public string name { get; set; }
        public Nullable<decimal> salary_from { get; set; }
        public Nullable<decimal> salary_to { get; set; }
        public string computation { get; set; }
        public Nullable<decimal> employee_contribution { get; set; }
        public Nullable<decimal> employer_contribution { get; set; }
        public bool flat_rate { get; set; }
        public Nullable<System.DateTime> date_deleted { get; set; }
    }
}
