//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_day_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ref_day_type()
        {
            this.employee_timesheet = new HashSet<employee_timesheet>();
        }
    
        public int ref_day_type_id { get; set; }
        public string date_type_code { get; set; }
        public string date_type_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_timesheet> employee_timesheet { get; set; }
    }
}
