//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_calendar_activity
    {
        public int ref_calendar_activity_id { get; set; }
        public Nullable<System.DateTime> work_date { get; set; }
        public Nullable<int> ref_day_type_id { get; set; }
        public Nullable<System.DateTime> date_deleted { get; set; }
    }
}
