//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class timesheet_log
    {
        public long timesheet_log_id { get; set; }
        public string employee_serial { get; set; }
        public Nullable<System.DateTime> datetime_in { get; set; }
        public Nullable<System.DateTime> datetime_out { get; set; }
    }
}
