using Microsoft.SqlServer.Types;
using System;
using System.Collections.Generic;

namespace Payroll.Infrastructure.Models
{
    public partial class ref_group
    {
        //Extend the ref_group to include SqlHierarchyId since this is not generated by Scaffold-DbContext
        public SqlHierarchyId level { get; set; }
    }
}
